using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectEulerAPI.Models.EulerProblems
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    /// <returns>4613732</returns>
    public class EulerProblem2 : IEulerProblem
    {
        public int GetResult()
        {

            int first = 1;
            int second = 2;

            int sum = 0;

            while (second < 4000000)
            {
                if (second % 2 == 0)
                    sum += second;

                // 5 = 3 + 2
                int fibonacci = first + second;

                // 3 = second, 2 = first
                first = second;
                second = fibonacci;
            }

            return sum;
        }
    }
}
